spring:
  application:
    name: bank-account-api
  main:
    banner-mode: console
  banner:
    location: classpath:/banner.txt
  output:
    ansi:
      enabled: always
  jackson:
    date-format: 'dd.MM.yyyy'

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:bank_account_db;DATABASE_TO_LOWER=true
    password: # leave password field empty for Server Mode connection
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: false
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false

axon:
  axonserver:
    servers: localhost:8124  # pointing to the Axon Server and gRPC port
  serializer:
    general: jackson

springdoc:
  dev-url: http://localhost:8080
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha

exception:
  trace: true

logging:
  file:
    name: './logs/application.log'
    logback:
      rollingpolicy:
        max-file-size: 1MB
        total-size-cap: 10MB
        max-history: 30
        clean-history-on-start: true
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %clr(%m){faint}%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  level:
    com.github.yildizmy: debug
    org.springframework: warn
    org.hibernate: error